shifts:
  [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
volunteers:
  - name: Flavio Corpa
    availability:
      [JT, VT, SM, SMD]
    pioneer: true
  - name: Lidia Corpa
    availability:
      [MM, VT, SM, SMD]
    pioneer: true
  - name: Julián Porta
    availability:
      [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Celia Porta
    availability:
      [XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Juan Pedro Ruiz
    availability: [XT, SM, SMD]
    pioneer: false
  - name: Joaquina Ruiz
    availability: [SM, SMD, D]
    pioneer: false
  - name: Miguel García
    availability: [SM, SMD, D]
    pioneer: false
  - name: Carmen García
    availability: [JT, SM, SMD, D]
    pioneer: false
  - name: David Cantó
    availability:
      [XT, VT]
    pioneer: false
  - name: Priscila Cantó
    availability: [VT]
    pioneer: true
  - name: Mery Lerebours
    availability:
      [MM, XT, JM, JMD, JT, VT, SM, SMD]
    pioneer: true
  - name: Manuel Pastorino
    availability:
      [XT, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Raquel Pastorino
    availability:
      [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Jairo Navarro
    availability: [VT, SM, SMD]
    pioneer: true
  - name: Kristel Navarro
    availability: [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Yézer Mellado
    availability:
      [VT, SM, SMD]
    pioneer: false
  - name: Queren Mellado
    availability: [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Marina Candela
    availability: [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Esteban Candela
    availability: []
    pioneer: false
  - name: Karen Gutiérrez
    availability: [MM, XT, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Juan Parra
    availability:
      [SMD, D]
    pioneer: false
  - name: Carol Parra
    availability: [MM, XT, JT, VT, SMD, D]
    pioneer: true
  - name: David Infantes
    availability:
      [XT, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Raquel Infantes
    availability: [MM, XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Nerea Infantes
    availability: [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Salud Fernández
    availability: []
    pioneer: true
  - name: Luis Mira
    availability: [SM, SMD, D]
    pioneer: false
  - name: July Mira
    availability: [JM, JMD, SM, SMD, D]
    pioneer: true
  - name: Antonio Cortés
    availability: [XT, JT, VT, SM, SMD]
    pioneer: true
  - name: Clarisa Cortés
    availability: [SM, SMD]
    pioneer: false
  - name: Clara Cortés
    availability:
      [XT, VT, SM, SMD, D]
    pioneer: true
  - name: Conan Martínez
    availability:
      [MM, JM, JMD]
    pioneer: false
  - name: Juani Martínez
    availability: [MM, JM, JMD]
    pioneer: true
  - name: Daniel Jiménez
    availability: [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Masha Jiménez
    availability: [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Ana García
    availability: [XT, VT] # a partir del día 20
    pioneer: false
  - name: José David Rodríguez
    availability: [XT, SM, SMD]
    pioneer: false
  - name: Rebeca Rodríguez
    availability: [MM, JM, JMD, SM, SMD]
    pioneer: true
  - name: Mari Carmen García
    availability: [SM, SMD]
    pioneer: false
  - name: Mara Herrero
    availability: [MM, SM, SMD, D]
    pioneer: true
  - name: María José González
    availability: [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Berushka López
    availability: [XT, VT, SM, SMD]
    pioneer: false
  - name: Maribel Moreno
    availability: [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: José Sánchez
    availability:
      []
    pioneer: false
  - name: Silvia Sánchez
    availability: [XT, JT, VT]
    pioneer: true
  - name: Gabriel Sánchez
    availability:
      [JM, JMD, SM, SMD]
    pioneer: false
  - name: Abraham Brotons
    availability: [SM, SMD, D]
    pioneer: false
  - name: Amalín Brotons
    availability: [MM, XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Laura Brotons
    availability: [XT, JT, VT, SM, SMD]
    pioneer: true
  - name: María Jesús Pol
    availability: []
    pioneer: false
  - name: Loli Sánchez
    availability: [MM, MT, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Miguel Robles
    availability: [XT, JT, VT, SM, SMD]
    pioneer: true
  - name: Pati Robles
    availability: [XT, JT, VT, SM, SMD]
    pioneer: true
  - name: Mari Ripoll
    availability:
      [XT, JT, VT, SM, SMD]
    pioneer: false
  - name: José Antonio Ripoll
    availability:
      [MM, XT, VT, D]
    pioneer: false
  - name: Verónica Estarlich
    availability: []
    pioneer: true
  - name: Pepi Esteve
    availability:
      [MM, MT, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Salomé Lobato
    availability:
      [D]
    pioneer: true
  - name: Carlos Ribón
    availability:
      [XT, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Margie Ribón
    availability: [MM, MT, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Julio Ribón
    availability: [MM, MT, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: false
  - name: José Antonio Santos
    availability: [XT, SM, SMD, D]
    pioneer: false
  - name: Ana Santos
    availability: [XT, JT, VT, SM, SMD, D]
    pioneer: true
  - name: Ethan Córdoba
    availability: [SM, SMD, D]
    pioneer: false
  - name: Paula Córdoba
    availability: [SM, SMD, D]
    pioneer: false
  - name: Mauricio Delgado
    availability: [SM, SMD, D]
    pioneer: false
  - name: Tammy Delgado
    availability: [SM, SMD, D]
    pioneer: false
  - name: Pilar Heredia
    availability: [MM, XT, JM, JMD, JT, VT, SM, SMD, D]
    pioneer: false
  - name: Mari Carmen Avilés
    availability: []
    pioneer: true
  - name: Carmen Maciá
    availability: []
    pioneer: true
  - name: Nadir Tiago
    availability: []
    pioneer: true
