shifts: [M, T, W, H, F, S]
volunteers:
  - name: Flavio
    availability: [S]
  - name: Lydia
    availability: [M, T, H, F, S]
  - name: Eva
    availability: [M, T, W, H, F, S]
  - name: Pedro
    availability: [M, T, H, F, S]
  - name: Jennifer
    availability: [T, S]
  - name: Desirée
    availability: [M, T, W, F, S]
  - name: Sergio
    availability: [M, T, F, S]
  - name: Marisa
    availability: [M, T]
  - name: Terry
    availability: [T, W, H, F, S]
  - name: Janet
    availability: [T, W, H, F, S]
  - name: Stephanie
    availability: [W, S]
  - name: Alfonso
    availability: [W, S]
  - name: Nadia
    availability: [W, S]
  - name: Esther
    availability: [W, H]
  - name: Magdalena
    availability: [S]
  - name: Violeta
    availability: [F]
  - name: Yolanda
    availability: [M]
  - name: Mercedes
    availability: [S]
  - name: Richard
    availability: [S]
  - name: Jean Paul
    availability: [S]
  - name: Vida
    availability: [S]
  - name: Jaziel
    availability: [S]
  - name: Chikkaola
    availability: [S]
  - name: Comfort
    availability: [T, W, S]
  - name: Jim
    availability: [W, H]
  - name: Enrique
    availability: [S]
  - name: Linda
    availability: [T, H, S]
  - name: David
    availability: [T, H, S]
